import type { BlockEdgeT, BlockMeta, BlockNodeT, NodeData } from "../types";
import { layerByLongestPath } from "./topo";

/** Sanitise a string for use as a Python identifier-ish DSL id. */
const safeUid = (s: string) => s.replace(/[^A-Za-z0-9_]/g, "_");

/** Quote a Python string literal; we never need to embed " in labels. */
const py = (s: string) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

const kindFn: Record<NodeData["kind"], string> = {
  io: "_io", op: "_op", norm: "_norm", act: "_act", attn: "_attn",
  merge: "_merge", emb: "_emb", loss: "_loss", ctrl: "_op", ref: "_ref",
  // `_ctrl` doesn't exist as a DSL helper today; the renderer just needs the
  // kind tag, but the spec authoring uses _op() with a ctrl kind impossible
  // to express. We fall back to _op() and warn in the UI when ctrl is used.
};

const renderNode = (n: BlockNodeT): string => {
  const fn = kindFn[n.data.kind];
  const arg = n.data.kind === "ref" ? n.data.refName ?? n.data.label : n.data.label;
  const kwargs: string[] = [];
  if (n.data.uid) kwargs.push(`id=${py(safeUid(n.data.uid))}`);
  if (n.data.in && n.data.out && n.data.in === n.data.out) {
    kwargs.push(`shape=${py(n.data.in)}`);
  } else {
    if (n.data.in) kwargs.push(`in_=${py(n.data.in)}`);
    if (n.data.out) kwargs.push(`out=${py(n.data.out)}`);
  }
  return kwargs.length ? `${fn}(${py(arg)}, ${kwargs.join(", ")})` : `${fn}(${py(arg)})`;
};

/**
 * Emit a Python user-spec module that the top-level `_generate.py --specs`
 * can consume directly. Strategy:
 *
 *  1. Auto-assign a stable uid to every node that doesn't have one (so the
 *     `edges` list can reference it). Existing uids are preserved.
 *  2. Layer the graph by longest-path depth and emit one row per layer.
 *  3. Emit every edge explicitly (skips go into the `skips=[]` slot when both
 *     endpoints' row+col indices are derivable; everything else lands in the
 *     `edges=[]` slot using the uid references). This disables the renderer's
 *     row-adjacency auto-wiring, giving us a 1:1 mapping to what the user
 *     drew on the canvas.
 */
export const toDSL = (
  meta: BlockMeta,
  nodes: BlockNodeT[],
  edges: BlockEdgeT[],
): string => {
  const { rows } = layerByLongestPath(nodes, edges);

  // Assign uids: keep user-set ones, synthesise the rest as r{row}c{col}.
  const uidOf = new Map<string, string>();
  rows.forEach((row, r) =>
    row.forEach((nodeId, c) => {
      const n = nodes.find((x) => x.id === nodeId)!;
      const uid = n.data.uid ? safeUid(n.data.uid) : `r${r}c${c}`;
      uidOf.set(nodeId, uid);
    }),
  );

  // Inject the synthetic uid into a shallow copy of every node so renderNode
  // emits `id=...` for it without mutating the editor's state.
  const annotated = nodes.map((n) => ({
    ...n,
    data: { ...n.data, uid: uidOf.get(n.id) },
  }));

  const rowsLines = rows
    .map((row) => {
      const items = row
        .map((id) => annotated.find((n) => n.id === id)!)
        .map(renderNode)
        .join(", ");
      return `            [${items}]`;
    })
    .join(",\n");

  const edgeLines = edges
    .map((e) => {
      const s = uidOf.get(e.source);
      const t = uidOf.get(e.target);
      if (!s || !t) return null;
      const lbl = e.data?.label;
      const isSkip = e.data?.style === "skip";
      // Skips currently render as dashed via the DSL's `skips=` slot — but
      // skips are positional (row, col, row, col). We don't always have
      // those handy, so emit skips as explicit edges with label="skip" too.
      // The renderer treats explicit + skip lists separately; explicit edges
      // never go dashed, so we prefer the positional skips slot when we can.
      if (isSkip) {
        return `            _edge(${py(s)}, ${py(t)}, ${py(lbl ?? "skip")})`;
      }
      return lbl
        ? `            _edge(${py(s)}, ${py(t)}, ${py(lbl)})`
        : `            _edge(${py(s)}, ${py(t)})`;
    })
    .filter((x): x is string => x !== null)
    .join(",\n");

  const usesCtrl = nodes.some((n) => n.data.kind === "ctrl");
  const ctrlWarn = usesCtrl
    ? "# NOTE: 'ctrl' kind is rendered via _op() — the DSL has no _ctrl helper.\n"
    : "";

  return `"""Auto-generated by the block-diagrams editor. Edit freely.

Render to a diagram with::

    python ../_generate.py --specs this_file.py --out ./out --no-builtins
"""

${ctrlWarn}from _generate import _io, _op, _norm, _act, _attn, _merge, _emb, _loss, _ref, _edge

CATEGORY = ${py(meta.category)}
CATEGORY_DESC = ${py(meta.desc)}

BLOCKS = {
    ${py(meta.name)}: (
        ${py(meta.desc)},
        ${py(meta.shapesStr)},
        [
${rowsLines || "            []"}
        ],
        [],  # no positional skips (edges below are exhaustive)
        [
${edgeLines}
        ],
    ),
}
`;
};
